FROM alpine:3.21 AS builder

COPY ./frp.tar.gz /build/
WORKDIR /build/
RUN tar -zxvf frp.tar.gz --strip-components 1 \
    && mkdir -p conf bin \
    && cp frps.toml conf \
    && cp frpc bin 


FROM alpine:3.21

LABEL maintainer="xbhel@outlook.com"

EXPOSE 7000:7000
COPY --from=builder /build/bin /build/conf /opt/frp/

ENTRYPOINT ["/opt/frp/bin/frpc"]
CMD ["-c", "/opt/frp/conf/frpc.toml"]