FROM alpine:3.21

WORKDIR /build
COPY frp.tar.gz .
RUN tar -zxvf frp.tar.gz --strip-components 1 \
    && cp frps /usr/bin/frps \
    && rm -rf /build/ 

WORKDIR /
EXPOSE 7000
ENTRYPOINT ["/usr/bin/frps"]
CMD ["-c", "/opt/frp/conf/frps.toml"]